version: '3'

services:

  broker-service:
    image: gotalkie/go-talkie-broker
    #    build:
      #  context: go-talkie-broker
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    image: gotalkie/go-talkie-auth
    #    build:
    #  context: go-talkie-auth
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  mysql-db:
    image: mysql:latest
    env_file:
      - go-talkie-auth/.env
    restart: always
    # keep these commented as we do not want to expose that to the world - uncomment only for debug purposes
    ports:
      - '3306:3306'
    # expose:
    #   - 3306
    volumes:
      - my-db:/var/lib/mysql
      - "./schema.sql:/docker-entrypoint-initdb.d"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
volumes:
  my-db:
