version: '3'

services:

  broker-service:
    build:
      context: go-talkie-broker
      dockerfile: broker.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    build:
      context: go-talkie-auth
      dockerfile: auth-app.dockerfile
    restart: always
    ports:
    - "8081:80"
    deploy:
      mode: replicated
      replicas: 1

  mysql-db:
    image: mysql:5.7
    env_file:
      - go-talkie-auth/.env
    restart: always
    # keep these commented as we do not want to expose that to the world - uncomment only for debug purposes
    # ports:
    #   - '3306:3306'
    # expose:
    #   - 3306
    volumes:
      - my-db:/var/lib/mysql
      - "./sql_initScripts:/docker-entrypoint-initdb.d"

volumes:
  my-db: