kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-db-volume
  labels:
    type: local
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/home/kristof/GoTalkie/go-talkie-main/sql_initScripts/"